# mpv-http-ytproxy configuration file
# Performance-optimized configuration with human-readable sizes

[proxy]
port = 12081
chunk_size = "10MB"      # Default: 10MB for optimal balance (10,485,760 bytes)
cert_file = "cert.pem"
key_file = "key.pem"
adaptive_chunking = false
min_chunk_size = "2.5MB"  # Minimum chunk size (2,621,440 bytes)
max_chunk_size = "40MB"   # Maximum chunk size (41,943,040 bytes)

[security]
cert_validity_days = 365

[logging]
level = "info"
log_timing = false

[performance]
http2 = false
connection_pool_size = 10
request_timeout = 30
enable_compression = false

# Size Format Examples:
# - Numbers: 1024, 10485760 
# - With units: 10KB, 10MB, 1GB, 2TB
# - Short units: 10K, 10M, 1G, 2T
