# mpv-http-ytproxy configuration file
# Performance-optimized configuration example

[proxy]
port = 12081
chunk_size = 20971520  # 20MB for better performance
cert_file = "cert.pem"
key_file = "key.pem"
adaptive_chunking = true
min_chunk_size = 5242880   # 5MB
max_chunk_size = 52428800  # 50MB

[security]
cert_validity_days = 365

[logging]
level = "info"
log_timing = true

[performance]
http2 = true
connection_pool_size = 15
request_timeout = 60
enable_compression = true
